name: Tests
run-name: |
  Test workflow

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  workflow_dispatch:

jobs:
  
  unit-tests:

    runs-on: self-hosted
    steps:

    - name: Check out repository
      uses: actions/checkout@v3
      with:
        path: app
      
    - name: Run tests with Thread Sanitizer
      env:
        SWIFT_DETERMINISTIC_HASHING: 1
      run: |
        swift test \
          --parallel \
          --enable-code-coverage \
          --sanitize=thread
      working-directory: app
  
  